name: Run the tests

on: [pull_request]

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-java@v4.4.0
        with:
          java-version: 21
          distribution: oracle

      - name: Install dependencies
        run: mvn clean install -DskipTests=true --no-transfer-progress

      - name: Install test dependencies
        run: mvn test -DskipTests=true --no-transfer-progress

  tests:
    needs: install_dependencies
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test_class:
          # Codecs
          - "com.ex_dock.ex_dock.codecs.template_engine.SingleUseTemplateDataCodecTest"

          # Templating Engine
          - "com.ex_dock.ex_dock.frontend.template_engine.TemplateEngineVerticleSingleUseTest"

          # Database
          ## Account
          - "com.ex_dock.ex_dock.database.account.AccountJdbcVerticleTest"
          ## Category
          - "com.ex_dock.ex_dock.database.category.CategoryJdbcVerticleTest"
          ## Product
          - "com.ex_dock.ex_dock.database.product.ProductCustomAttributesJdbcVerticleTest"
          - "com.ex_dock.ex_dock.database.product.ProductGlobalEavJdbcVerticleTest"
          - "com.ex_dock.ex_dock.database.product.ProductJdbcVerticleTest"
          - "com.ex_dock.ex_dock.database.product.ProductMultiSelectJdbcVerticleTest"
          - "com.ex_dock.ex_dock.database.product.ProductStoreViewEavJdbcVerticleTest"
          - "com.ex_dock.ex_dock.database.product.ProductWebsiteEavJdbcVerticleTest"
          ## Scope
          - "com.ex_dock.ex_dock.database.scope.ScopeJdbcVerticleTest"
          ## Server
          - "com.ex_dock.ex_dock.database.server.ServerJdbcVerticleTest"
          ## TextPages
          - "com.ex_dock.ex_dock.database.text_pages.TextPagesJdbcVerticleTest"
          ## Url
          #          - "com.ex_dock.ex_dock.database.url.UrlJdbcVerticleTest"
          ## Utils
          - "com.ex_dock.ex_dock.database.utils.JdbcSetupTest"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup
        uses: actions/setup-java@v4.4.0
        with:
          java-version: 21
          distribution: oracle

      - name: Run Tests
        run: |
          ls
          docker compose -f .ci/compose.yaml -p ci up -d --quiet-pull
          mvn test -Dtest=${{ matrix.test_class }} --no-transfer-progress
